;;;
;;; Video driver
;;; 
;;; Cursor: (x, y) = ($2002, $2003)
;;; (The addresses are generated by an I/O mapped accelerator.)
;;; Current character address: $2004
;;; Current color address: $2006

;;; Initialize video
vga_init:
	;; Reset cursor position
	LDA #0 		
	STA $2002
	STA $2003
	RTS

;;; Write string pointed to by A(lsb) and Y(msb)
vga_put_str:
	STA $40
	STY $41
	LDX #0			; Init counter
	LDY #$F0 		; Set color to black/white
vga_put_str_loop:	
	LDA ($40),X		; Load char
	CMP #0			
	BEQ vga_put_str_end
	JSR vga_put_char
	INX
	JMP vga_put_str_loop
vga_put_str_end:
	RTS
	
;;; Write char in A with color Y to current cursor position
;;; and increment cursor.
vga_put_char:
	STA ($2004)
	STY ($2006)
	JSR vga_inc_cursor
	RTS

;;; Increment cursor
vga_inc_cursor:
	LDA $2002
	CMP #79
	BEQ vga_inc_cursor_row
	ADC #1
	STA $2002
	RTS
vga_inc_cursor_row:
	LDA #0
	STA $2002
	LDA $2003
	CMP #59
	BEQ vga_inc_cursor_wrap
	ADC #1
	STA $2003
	RTS
vga_inc_cursor_wrap:	
	LDA #0
	STA $2003
	RTS
